# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QColor
import os
from allfuncs import receive_message


#get token from token.txt
with open("../bot-token/token.txt", "r") as f:
    Token = f.readline()
    f.close()



class Ui_MainWindow(object):
    from allfuncs import receive_message
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(894, 723)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color:rgb(217, 217, 217)")
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.SenderDisplay = QtWidgets.QTextBrowser(self.centralwidget)
        self.SenderDisplay.setEnabled(True)
        self.SenderDisplay.setGeometry(QtCore.QRect(630, 90, 256, 301))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.SenderDisplay.setFont(font)
        self.SenderDisplay.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.SenderDisplay.setAutoFillBackground(True)
        self.SenderDisplay.setStyleSheet("background-color:rgb(0, 0, 0)")
        self.SenderDisplay.setReadOnly(True)
        self.SenderDisplay.setObjectName("SenderDisplay")
        self.LogDisplay = QtWidgets.QTextBrowser(self.centralwidget)
        self.LogDisplay.setGeometry(QtCore.QRect(10, 600, 741, 121))
        self.LogDisplay.setStyleSheet("background-color:rgb(0, 0, 0)")
        self.LogDisplay.setObjectName("LogDisplay")
        self.TokenLabel = QtWidgets.QLabel(self.centralwidget)
        self.TokenLabel.setGeometry(QtCore.QRect(120, 10, 511, 31))
        self.TokenLabel.setObjectName("TokenLabel")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 60, 141, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(690, 60, 131, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(390, 60, 131, 20))
        self.label_4.setObjectName("label_4")
        self.EditButton = QtWidgets.QPushButton(self.centralwidget)
        self.EditButton.setGeometry(QtCore.QRect(10, 10, 93, 28))
        self.EditButton.setStyleSheet("background-color:rgb(255, 0, 0)")
        self.EditButton.setObjectName("EditButton")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(630, 400, 55, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(630, 430, 91, 16))
        self.label_6.setObjectName("label_6")
        self.Userid = QtWidgets.QLineEdit(self.centralwidget)
        self.Userid.setGeometry(QtCore.QRect(690, 400, 161, 22))
        self.Userid.setObjectName("Userid")
        self.SendButton = QtWidgets.QPushButton(self.centralwidget)
        self.SendButton.setGeometry(QtCore.QRect(830, 510, 51, 41))
        self.SendButton.setStyleSheet("background-color:rgb(0, 194, 0)")
        self.SendButton.setObjectName("SendButton")
        self.MessageText = QtWidgets.QTextEdit(self.centralwidget)
        self.MessageText.setGeometry(QtCore.QRect(630, 450, 181, 101))
        self.MessageText.setStyleSheet("background-color:rgb(154, 154, 154)")
        self.MessageText.setObjectName("MessageText")
        self.ReceiverDisplay = QtWidgets.QTextBrowser(self.centralwidget)
        self.ReceiverDisplay.setEnabled(True)
        self.ReceiverDisplay.setGeometry(QtCore.QRect(10, 90, 261, 301))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.ReceiverDisplay.setFont(font)
        self.ReceiverDisplay.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.ReceiverDisplay.setAutoFillBackground(True)
        self.ReceiverDisplay.setStyleSheet("background-color:rgb(0, 0, 0)")
        self.ReceiverDisplay.setReadOnly(True)
        self.ReceiverDisplay.setObjectName("ReceiverDisplay")
        self.AutoDisplay = QtWidgets.QTextBrowser(self.centralwidget)
        self.AutoDisplay.setEnabled(True)
        self.AutoDisplay.setGeometry(QtCore.QRect(320, 90, 256, 301))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.AutoDisplay.setFont(font)
        self.AutoDisplay.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.AutoDisplay.setAutoFillBackground(True)
        self.AutoDisplay.setStyleSheet("background-color:rgb(0, 0, 0)")
        self.AutoDisplay.setReadOnly(True)
        self.AutoDisplay.setObjectName("AutoDisplay")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(279, 50, 31, 511))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(590, 50, 21, 521))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(7, 556, 881, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(10, 40, 881, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.StartReceiver = QtWidgets.QPushButton(self.centralwidget)
        self.StartReceiver.setGeometry(QtCore.QRect(30, 400, 221, 28))
        self.StartReceiver.setStyleSheet("background-color:rgb(85, 255, 0)")
        self.StartReceiver.setObjectName("StartReceiver")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 470, 271, 91))
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 570, 55, 21))
        self.label_7.setObjectName("label_7")
        self.StartAuto = QtWidgets.QPushButton(self.centralwidget)
        self.StartAuto.setGeometry(QtCore.QRect(340, 400, 91, 41))
        self.StartAuto.setStyleSheet("background-color:rgb(85, 255, 0)")
        self.StartAuto.setObjectName("StartAuto")
        self.StopAuto = QtWidgets.QPushButton(self.centralwidget)
        self.StopAuto.setGeometry(QtCore.QRect(470, 400, 91, 41))
        self.StopAuto.setStyleSheet("background-color:rgb(255, 26, 26)")
        self.StopAuto.setObjectName("StopAuto")
        self.StopReceiver = QtWidgets.QPushButton(self.centralwidget)
        self.StopReceiver.setGeometry(QtCore.QRect(30, 440, 221, 28))
        self.StopReceiver.setStyleSheet("background-color:rgb(255, 26, 26)")
        self.StopReceiver.setObjectName("StopReceiver")
        self.AddAnswer = QtWidgets.QPushButton(self.centralwidget)
        self.AddAnswer.setGeometry(QtCore.QRect(340, 470, 221, 51))
        self.AddAnswer.setStyleSheet("background-color:rgb(255, 122, 34)")
        self.AddAnswer.setObjectName("AddAnswer")
        self.About = QtWidgets.QPushButton(self.centralwidget)
        self.About.setGeometry(QtCore.QRect(842, 680, 51, 41))
        self.About.setObjectName("About")
        self.LogDisplay.raise_()
        self.SenderDisplay.raise_()
        self.TokenLabel.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.EditButton.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.Userid.raise_()
        self.SendButton.raise_()
        self.MessageText.raise_()
        self.ReceiverDisplay.raise_()
        self.AutoDisplay.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.line_4.raise_()
        self.StartReceiver.raise_()
        self.label.raise_()
        self.label_7.raise_()
        self.StartAuto.raise_()
        self.StopAuto.raise_()
        self.StopReceiver.raise_()
        self.AddAnswer.raise_()
        self.About.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.SendButton.clicked.connect(self.SendButton.deleteLater) # type: ignore
        self.EditButton.clicked.connect(self.EditToken) # type: ignore
        self.StartReceiver.clicked.connect(self.receive_message) # type: ignore
        self.StopReceiver.clicked.connect(self.StopReceiver.deleteLater) # type: ignore
        self.StartAuto.clicked.connect(self.StartAuto.deleteLater) # type: ignore
        self.StopAuto.clicked.connect(self.StopAuto.deleteLater) # type: ignore
        self.AddAnswer.clicked.connect(self.AddAnswer.deleteLater) # type: ignore
        self.About.clicked.connect(self.About.deleteLater) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

# how "Edit Token" Button works:
    def EditToken(self):
        with open("../bot-token/recieved.txt", "w") as edit:
            edit.write("0")
            edit.close()
            os.startfile("..\\bot-token\\token.py")
            exit()
            

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SenderDisplay.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.SenderDisplay.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.TokenLabel.setText(_translate("MainWindow", f"<html><head/><body><p><span style=\" font-size:9pt;\">Your Bot Token is: {Token}</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#424242;\">Receive Message </span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#424242;\">Send Message </span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#424242;\">Automatic reply</span></p></body></html>"))
        self.EditButton.setText(_translate("MainWindow", "Edit Token"))
        self.label_5.setText(_translate("MainWindow", "User id :"))
        self.label_6.setText(_translate("MainWindow", "Your Message :"))
        self.SendButton.setText(_translate("MainWindow", "Send"))
        self.ReceiverDisplay.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.ReceiverDisplay.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.AutoDisplay.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.AutoDisplay.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.StartReceiver.setText(_translate("MainWindow", "Start Receiver"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">Your Receiver Will Refresh Automatically </span></p><p><span style=\" font-size:9pt;\">Every </span><span style=\" font-size:9pt; color:#ff1a1a;\">5</span><span style=\" font-size:9pt;\"> Seconds.</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#000000;\">Log :</span></p></body></html>"))
        self.StartAuto.setText(_translate("MainWindow", "Start "))
        self.StopAuto.setText(_translate("MainWindow", "Stop"))
        self.StopReceiver.setText(_translate("MainWindow", "Stop Receiver"))
        self.AddAnswer.setText(_translate("MainWindow", "Add New Answer"))
        self.About.setText(_translate("MainWindow", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())






