# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'token.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
import time

with open("recieved.txt", "r") as entered:
    if (entered.readline() == "1"):
        entered.close()
        os.startfile("..\\tel-bot\main.py")
        exit()


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(756, 241)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.inp = QtWidgets.QLineEdit(self.centralwidget)
        self.inp.setGeometry(QtCore.QRect(190, 90, 541, 31))
        self.inp.setObjectName("inp")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 100, 171, 16))
        self.label.setObjectName("label")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(680, 190, 61, 41))
        self.submit.setObjectName("submit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.submit.clicked.connect(self.submit_token) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def submit_token(self):
        app.processEvents()
        with open("token.txt", "w") as file:
            file.write(self.inp.text())
            file.close()

        with open("recieved.txt", "w") as log:
            log.write("1")
            log.close()

        time.sleep(1.5)
        os.startfile("..\\tel-bot\main.py")
        exit()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Token Saver"))
        self.label.setText(_translate("MainWindow", "Please Enter Your Bot Token:"))
        self.submit.setText(_translate("MainWindow", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
